export enum Role {
  VENDEUR = 'VENDEUR',
  ACHETEUR = 'ACHETEUR',
  VETERINAIRE = 'VETERINAIRE',
  AGENT_ANADER = 'AGENT_ANADER',
  ADMINISTRATEUR = 'ADMINISTRATEUR',
  ADMIN = 'ADMIN',
  USER = 'USER',
}
