spring.application.name=marketplace-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=marketplace
spring.datasource.password=marketplace

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:flyway/schema,classpath:flyway/dev


#jwt.secret=marketplaceSecretKeyForJwtTokenGeneration2026VeryLongAndSecureKeyForHs512
jwt.secret=${JWT_SECRET:marketplaceSecretKeyForJwtTokenGeneration2026VeryLongAndSecureKeyForHs512}
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

app.storage.base-dir=${user.home}/marketplace-betail-poc/storage

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6Jw5WpQDuaw2ruh8eQh-FnZzkkMgQkurpCutFoUUEDyVQ}
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent


logging.level.com.marketplace=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.com.marketplace=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.root=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=skabore2020@gmail.com 
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8

app.frontend.url=http://localhost:4200
app.backend.url=http://localhost:8080



